# Generated by Django 4.2.19 on 2025-05-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPFToken',
            fields=[
                ('token', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('cpf_real', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
