# Generated by Django 4.2.19 on 2025-05-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthDateToken',
            fields=[
                ('token', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('birth_date_real', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CPFToken',
            fields=[
                ('token', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('cpf_real', models.CharField(max_length=11, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('token', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('email_real', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneToken',
            fields=[
                ('token', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('phone_real', models.CharField(max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
