# Generated by Django 5.2 on 2025-05-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensitive_info', '0002_emailtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthDateToken',
            fields=[
                ('token', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('birth_date_real', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneToken',
            fields=[
                ('token', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('phone_real', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
