# Generated by Django 5.2 on 2025-05-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensitive_info', '0003_birthdatetoken_phonetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpftoken',
            name='cpf_real',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='emailtoken',
            name='email_real',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='phonetoken',
            name='phone_real',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
